dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install coveralls
before_script:
- invoke lint && invoke validateyaml
script:
- invoke test
after_success:
- coveralls
deploy:
  provider: script
  script: 'curl -X POST -H "Content-Type: application/json" --data ''{"docker_tag_name":
    "latest"}'' https://registry.hub.docker.com/u/brianmitchl/weatherbot/trigger/$DOCKER_HUB_TOKEN/'
  on:
    branch: master
branches:
  only:
  - development
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  global:
  - secure: Httle2zpXRyVPIdRZ2XE9WwdhdTicZBi7vltamQczSoiKK5MLquE9gUS5Vnyfs+8v58IiJdyfaRt2QG/03a3hf9F95BnVt00zWZKHLDpNgfDwRd1JMxIE+4ey+bcNVbcqNwQ7HvNcdknrV1NvBhkTtB5AUWKD3IK3fne7ziX0u0=
  - secure: ewQCeaJM/mq+gsIRjwtpnP+aGF7xY4//JIxi3moebRIASdeCiei7edN9wlsei6p2N7ENDPrAjdUQc8pejS282jc9lM9mDqkXuawozVRNvNQh9JkILBEhFHyGHLHFQJOHJ3b875oMY0Gtp9i0ETuf/vppUw3jXgg8ylgdv+yfklQ=
  - secure: Y69tiCnL2e37pb/8rTetVVK482sfg7AU1Vz5BRMursFSyUpes9rquCNXs6gAbAeNlENXZg9a/eE4FpYrGP5iIq4fLGDV3rnwmyf/Z4pzT33BgqYTp+44Np0zY7WKKJFGI2EW/z95DplKIwhP6BMokqNdqxvXampMAIev3jGIJeA=
  - secure: C0m2NE7Goy30ne31Xrxq9diob2SgTPZBkHT9VcuKcOR0bPs8w6qoQapsR6NgNNNW7d+kmQ8KQY7dyBO1k7rH2sJhcTPgVDoP8mac8Ill8pAX2sT1gap2tUpwEQXrG2hbfE5cXT+OCwBjSisMWHRfAwyzPn06eAfe+SRF4BRcQ9U=
  - secure: DOAbuJakg/OuwH/ySZJCkUyMrhVK/lodcIu6IE+nd3JdlHm86qBUm1dJVKKw81QBb9CLfpGt3oirvwAdwYpj8ZJ/M5VYTbaEmiUQMvKz6InyVcs1+Cf/Up1UhuUfRKyAUqzm4IFYUE00dbM563GwXOdN7o7Ofx6sBdMVnJR+a7M=
  - secure: BJ7xxMyifP6L2rQBsSsogJo5MsdkrZH1bHSJ6U8fJW7tLANgDMdeP5u6ItD3/LFgT1nSnoBcG+ZLVf22eMZV0Ej/DZjr8WKFbfKoiOdTVbQSHkkiYp7FQXMausDcOQwXE0eUxpsObGmcKQ4iD/zeUqziHf0L/zss1l8M5n4aCrU=
