language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=weatherBot test.py
after_success:
- coveralls
env:
  global:
  - secure: QIQYiGVxorHEvDIrSWsgA3Wa30R20sBA2GdoOam0uIGc5PuqF7UwgNEPPLbiJNOWZNr1sViWOt5i2ZMAJ8joWyAXj838sf6A3y37XhOKyB3h7zHGNVldxDFZ6BA6PG/Ai/21/QwYdKEXKqEItNazHqqRZwQjBzJAd40BxQSjAJ0=
  - secure: Jfv/iYhi/fYIkJCGovrhvRNkdwREXCgMGhpcSMPolM9qvVCQGQXnY4jebaTc8sZAczSy5rmDa3SVl9XzYYopPP+6zGQMh7kRmS5+yLN8jWUFNqKpwNiFcrXqqpip8VX5D+I5OiOveGIzOQOGqMLixVOcZuPWoW60GXz3rQVpxug=
  - secure: Iab9+Vq0fQ67jB3eftF+Lv44j9UMt5Nz5mgUyam8POeUPounFfS+gbplQzbu2U2Y17+zY0RauezGpsw6V+C3Pw4Bb2ebESvoyMFdCN9yKhPwJ8YfMSYqb1NAZBgYaa+EMCcqm+Wa62EuFBFobcnkUBXffx8sZLURQAMup6lgUTQ=
  - secure: g1Ez+6RsJZBIdgAbgK00eZdJGHrE/7Okb6s+z2MLIz2MSEUVhp9RvOFp5XWDB/0XUZOZs6xVdthvHZNzsvmNtFGU3FPJCp/KYuWGMRDbzMLS0cISSOWJpo6TQoSCF9379LAdqZaYn/pZ74SSxds16Q+AtssH7SuqupMsXpJPYfc=
  - secure: VmFEYYpWOLf1MviFVGBoyuuabbjiC/PxeZgGJUvp2OfKbMfreeQqU+WcM5H+SLjj6Er6ge4+iU30Z16VwUGTsukvkWRH/hzJTuWgMZ8KvNXAqt7kjynXWS4S39pR9D7wNfITWli1xw6t88ggwQBclGg0B4rZoi3aWXoz0eK2urI=
  - secure: bdzFwgKToOXVyX5WGOoN0eDyzBAB9PkcsqvLQv8Vc3nZ84XvwDFtVtEnaFuupXRP3SQOvM1KJ9ZVCYS/b0IeBRfoxLFYp7Qkw0j/hSu2551sfeKVuXi8Gpvo5ffZa+0eK95hTWMrBNK4xH6QpDXhRpyDYrt3axIXHKL/3MzNFrA=
